# Generated by Django 5.1.3 on 2024-11-11 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_content', models.TextField()),
                ('file_name', models.CharField(blank=True, max_length=400, null=True)),
                ('file_content', models.FileField(blank=True, null=True, upload_to='upload_content/')),
                ('file_type', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='content_type',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Chat.messagecontent'),
        ),
    ]
